name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  fmt:
    name: Format Check
    runs-on: node-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: node-latest
    strategy:
      matrix:
        rust: [stable, "1.85.0"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy -- --deny warnings

  audit:
    name: Security Audit
    runs-on: node-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-audit
        run: cargo install cargo-audit --locked
      - name: Run security audit
        run: cargo audit

  mirror-to-github:
    name: Mirror to GitHub
    needs: [fmt, clippy, audit]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: node-latest
    steps:
      - name: Mirror - Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirror - Push to GitHub
        env:
          GITHUB_PAT: ${{ secrets.MIRROR_GITHUB_PAT }}
        run: |
          git config --global user.email "mail@sapiens.engineering"
          git config --global user.name "Sapient Engineer"
          git remote add gh "https://x-access-token:$GITHUB_PAT@https://github.com/Sapiens-Engineering/flipper-zero-air-filter-reset.git"
          git fetch origin
          git push gh HEAD:master --force
